aws:
  sqs:
    accessKey: "${aws_sqs_accessKey}"
    secretKey: "${aws_sqs_secretKey}"
    region: "${aws_sqs_region}"
    queues:
      translated_dataqueue: "arn:aws:sqs:us-east-1:843981437160:translated_dataqueue"

db:
  mysql:
    host: "${db_host}"
    port: "${db_port}"
    user: "${db_user}"
    password: "${db_password}"
    database: "${db_name}"

rapidapi:
  key: "${rapidapi_key}"
  host: "translateai.p.rapidapi.com"